; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc < %s -mtriple=i686-unknown-unknown | FileCheck %s --check-prefixes=X86
; RUN: llc < %s -mtriple=x86_64-unknown-unknown | FileCheck %s --check-prefixes=X64

define i32 @bsr_inc_fold(i32 %input, i32 %initial) nounwind {
; X86-LABEL: bsr_inc_fold:
; X86:       # %bb.0:
; X86-NEXT:    movl {{[0-9]+}}(%esp), %ecx
; X86-NEXT:    leal 1(%ecx), %eax
; X86-NEXT:    addl $1, %ecx
; X86-NEXT:    je .LBB0_1
; X86-NEXT:  # %bb.2:
; X86-NEXT:    bsrl %eax, %eax
; X86-NEXT:    retl
; X86-NEXT:  .LBB0_1:
; X86-NEXT:    movl {{[0-9]+}}(%esp), %eax
; X86-NEXT:    retl
;
; X64-LABEL: bsr_inc_fold:
; X64:       # %bb.0:
; X64-NEXT:    movl %esi, %eax
; X64-NEXT:    incl %edi
; X64-NEXT:    bsrl %edi, %eax
; X64-NEXT:    retq
  %add = add i32 %input, 1
  %cmp.i = icmp eq i32 %add, 0
  %1 = tail call range(i32 0, 33) i32 @llvm.ctlz.i32(i32 %add, i1 true)
  %sub.i = xor i32 %1, 31
  %cond.i = select i1 %cmp.i, i32 %initial, i32 %sub.i
  ret i32 %cond.i
}
