; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc < %s -mtriple=x86_64-- -mcpu=x86-64-v3 | FileCheck %s --check-prefixes=X64

define dso_local i32 @t13(ptr nofree noundef readonly captures(none) %a) local_unnamed_addr {
; X64-LABEL: t13:
; X64:       # %bb.0: # %entry
; X64-NEXT:    movl (%rdi), %ecx
; X64-NEXT:    leal -1(%rcx), %eax
; X64-NEXT:    xorl %ecx, %eax
; X64-NEXT:    cmpl $1, %ecx
; X64-NEXT:    sbbl $3, %eax
; X64-NEXT:    retq
entry:
  %0 = load i32, ptr %a, align 4
  %sub.i = add i32 %0, -1
  %xor.i = xor i32 %sub.i, %0
  %cmp = icmp eq i32 %0, 0
  %conv.neg = sext i1 %cmp to i32
  %1 = add i32 %xor.i, -3
  %2 = add i32 %1, %conv.neg
  ret i32 %2
}
